Repository getsolus/packages, pull requests merged in 2024-12, with the labels that each got.

#4515 github-cli: Update to v2.63.1
  packages/g/github-cli/package.yml
  packages/g/github-cli/pspec_x86_64.xml
Labels: Type: Security

#4187 python-zope.hookable: Update to v7.0
  packages/py/python-zope.exceptions/package.yml
  packages/py/python-zope.exceptions/pspec_x86_64.xml
  packages/py/python-zope.hookable/abi_used_symbols
  packages/py/python-zope.hookable/monitoring.yml
  packages/py/python-zope.hookable/package.yml
  packages/py/python-zope.hookable/pspec_x86_64.xml
  packages/py/python-zope.testrunner/files/dont-package-tests.patch
  packages/py/python-zope.testrunner/package.yml
  packages/py/python-zope.testrunner/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4543 sox: Update to 14.5.0 and rename to sox-ng
  packages/s/sox/abi_libs
  packages/s/sox/abi_symbols
  packages/s/sox_ng/MAINTAINERS.md
  packages/s/sox_ng/abi_libs
  packages/s/sox_ng/abi_symbols
  packages/s/sox_ng/abi_used_libs
  packages/s/sox_ng/abi_used_symbols
  packages/s/sox_ng/monitoring.yml
  packages/s/sox_ng/package.yml
  packages/s/sox_ng/pspec_x86_64.xml
Labels: Type: Security

#4547 sysstat: Update to v12.7.6
  packages/s/sysstat/abi_used_symbols
  packages/s/sysstat/monitoring.yml
  packages/s/sysstat/package.yml
  packages/s/sysstat/pspec_x86_64.xml
Labels: Type: Security

#4550 lenovo-legion-linux: Add at v0.0.18
  packages/l/lenovo-legion-linux/MAINTAINERS.md
  packages/l/lenovo-legion-linux/package.yml
  packages/l/lenovo-legion-linux/pspec_x86_64.xml
  packages/l/linux-current/REBUILDS.md
  packages/l/linux-current/autopush.yml
  packages/l/linux-lts/autopush.yml
Labels: Topic: Hardware Support, Topic: Kernel

#4634 wget: Update to v1.25.0
  packages/w/wget/files/CVE-2024-38428.patch
  packages/w/wget/package.yml
  packages/w/wget/pspec_x86_64.xml
Labels: Type: Security

#4652 prusa-slicer: Deprecate
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Topic: Sync Notes

#4661 thunar-media-tags-plugin: Add at v0.4.0
  packages/t/thunar-media-tags-plugin/MAINTAINERS.md
  packages/t/thunar-media-tags-plugin/abi_libs
  packages/t/thunar-media-tags-plugin/abi_symbols
  packages/t/thunar-media-tags-plugin/abi_used_libs
  packages/t/thunar-media-tags-plugin/abi_used_symbols
  packages/t/thunar-media-tags-plugin/monitoring.yml
  packages/t/thunar-media-tags-plugin/package.yml
  packages/t/thunar-media-tags-plugin/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4662 thunar-archive-plugin: Update to v0.5.2
  packages/t/thunar-archive-plugin/monitoring.yml
  packages/t/thunar-archive-plugin/package.yml
  packages/t/thunar-archive-plugin/pspec_x86_64.xml
  packages/x/xarchiver/files/xarchiver.metainfo.xml
  packages/x/xarchiver/package.yml
  packages/x/xarchiver/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4660 gtkhash: Build thunar plugin
  packages/g/gtkhash/abi_libs
  packages/g/gtkhash/abi_symbols
  packages/g/gtkhash/abi_used_libs
  packages/g/gtkhash/abi_used_symbols
  packages/g/gtkhash/files/msgfmt.patch
  packages/g/gtkhash/monitoring.yml
  packages/g/gtkhash/package.yml
  packages/g/gtkhash/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4705 wlr-randr: Add at v0.4.1
  packages/w/wlr-randr/MAINTAINERS.md
  packages/w/wlr-randr/abi_used_libs
  packages/w/wlr-randr/abi_used_symbols
  packages/w/wlr-randr/monitoring.yml
  packages/w/wlr-randr/package.yml
  packages/w/wlr-randr/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4706 add kanshi
  packages/k/kanshi/MAINTAINERS.md
  packages/k/kanshi/abi_used_libs
  packages/k/kanshi/abi_used_symbols
  packages/k/kanshi/monitoring.yml
  packages/k/kanshi/package.yml
  packages/k/kanshi/pspec_x86_64.xml
  packages/l/libscfg/abi_libs
  packages/l/libscfg/abi_symbols
  packages/l/libscfg/abi_used_libs
  packages/l/libscfg/abi_used_symbols
  packages/l/libscfg/monitoring.yml
  packages/l/libscfg/package.yml
  packages/l/libscfg/pspec_x86_64.xml
  packages/l/libvarlink/abi_libs
  packages/l/libvarlink/abi_symbols
  packages/l/libvarlink/abi_used_libs
  packages/l/libvarlink/abi_used_symbols
  packages/l/libvarlink/monitoring.yml
  packages/l/libvarlink/package.yml
  packages/l/libvarlink/pspec_x86_64.xml
Labels: Topic: Sync Notes
