Repository getsolus/packages, pull requests merged in 2024-02, with the labels that each got.

#1500 glibc: Update to v2.39
  packages/g/glibc/abi_symbols
  packages/g/glibc/abi_symbols32
  packages/g/glibc/files/0001-Compress-charmaps-with-zstd.patch
  packages/g/glibc/files/perf/0001-Use-KSM-for-the-BSS-segment-of-shared-libraries.patch
  packages/g/glibc/files/perf/0002-tune-adaptive-spin-count.patch
  packages/g/glibc/files/perf/0003-Malloc-tuning.patch
  packages/g/glibc/package.yml
  packages/g/glibc/pspec_x86_64.xml
Labels: Plumbing, Chore

#1300 systemd: Update to v254.8
  packages/s/systemd/abi_libs
  packages/s/systemd/abi_libs32
  packages/s/systemd/abi_symbols
  packages/s/systemd/abi_symbols32
  packages/s/systemd/abi_used_libs
  packages/s/systemd/abi_used_libs32
  packages/s/systemd/abi_used_symbols
  packages/s/systemd/abi_used_symbols32
  packages/s/systemd/files/0001-solus-Set-default-vconsole-font.patch
  packages/s/systemd/files/patches/clr/0015-more-udev-children-workers.patch
  packages/s/systemd/files/patches/clr/0025-Compile-udev-with-O3.patch
  packages/s/systemd/files/patches/clr/0029-Notify-systemd-earlier-that-resolved-is-ready.patch
  packages/s/systemd/files/patches/clr/0037-Make-timesyncd-a-simple-service.patch
  packages/s/systemd/files/patches/downstream/0001-Ensure-display-manager-can-reboot-while-inhibited-se.patch
  packages/s/systemd/files/patches/downstream/0002-systemctl-Don-t-emit-a-reload-warning-for-systemd-cr.patch
  packages/s/systemd/files/patches/downstream/0003-gpt-boot-generator-Do-not-automount-the-ESP-on-Solus.patch
  packages/s/systemd/files/patches/downstream/0004-Replace-etc-resolv.conf-with-systemd-resolved-symlin.patch
  packages/s/systemd/files/patches/downstream/0005-Don-t-try-to-set-nsswitch-and-don-t-attempt-to-butch.patch
  packages/s/systemd/files/patches/downstream/0006-sysusers-Explicitly-set-9-as-lp-ID.patch
  packages/s/systemd/files/patches/downstream/0007-journalctl-Only-show-info-messages-and-above.patch
  packages/s/systemd/files/patches/downstream/0008-login-Allow-more-active-permissions-to-prevent-permi.patch
  packages/s/systemd/files/patches/downstream/0009-path-lookup-Include-stateless-xdg-path-by-default.patch
  packages/s/systemd/files/patches/downstream/0010-Fix-swap-after-updating-util-linux.patch
  packages/s/systemd/files/patches/downstream/0011-Remove-unnecessary-log-readme.patch
  packages/s/systemd/files/patches/downstream/0012-remove-etc-issue-from-tmpfiles.patch
  packages/s/systemd/files/patches/downstream/0013-solus-Allow-default-font-to-be-set.patch
  packages/s/systemd/files/patches/downstream/0014-Solus-Ensure-var-log-journal-is-created.patch
  packages/s/systemd/files/patches/upstream/0001-vconsole-setup-port-to-main-func.h-boilerplate.patch
  packages/s/systemd/files/patches/upstream/0002-pid1-vconsole-setup-lock-dev-console-instead-of-the-.patch
  packages/s/systemd/files/patches/upstream/0003-vconsole-setup-use-a-consistent-log-level-when-setfo.patch
  packages/s/systemd/files/patches/upstream/0004-vconsole-setup-handle-the-case-where-the-vc-is-in-KD.patch
  packages/s/systemd/files/patches/upstream/0005-vconsole-setup-simplify-error-handling.patch
  packages/s/systemd/files/patches/upstream/0006-vconsole-setup-remember-the-correct-error-value-when.patch
  packages/s/systemd/files/patches/upstream/0007-Introduce-RET_GATHER-and-use-it-in-src-shared.patch
  packages/s/systemd/files/series
  packages/s/systemd/files/xdg-autostart-service-handle-gnome-autostart-on-kde.patch
  packages/s/systemd/monitoring.yml
  packages/s/systemd/package.yml
  packages/s/systemd/pspec_x86_64.xml
Labels: Plumbing, Priority: Normal, Chore

#1620 Bash v5.2
  packages/b/bash/abi_libs
  packages/b/bash/abi_symbols
  packages/b/bash/abi_used_libs
  packages/b/bash/abi_used_symbols
  packages/b/bash/files/bash51-001
  packages/b/bash/files/bash51-002
  packages/b/bash/files/bash51-003
  packages/b/bash/files/bash51-004
  packages/b/bash/files/bash51-005
  packages/b/bash/files/bash51-006
  packages/b/bash/files/bash51-007
  packages/b/bash/files/bash51-008
  packages/b/bash/files/bash51-009
  packages/b/bash/files/bash51-010
  packages/b/bash/files/bash51-011
  packages/b/bash/files/bash51-012
  packages/b/bash/files/bash51-013
  packages/b/bash/files/bash51-014
  packages/b/bash/files/bash51-015
  packages/b/bash/files/bash51-016
  packages/b/bash/files/series
  packages/b/bash/files/upstream/bash52-022
  packages/b/bash/files/upstream/bash52-023
  packages/b/bash/files/upstream/bash52-024
  packages/b/bash/files/upstream/bash52-025
  packages/b/bash/files/upstream/bash52-026
  packages/b/bash/package.yml
  packages/b/bash/pspec_x86_64.xml
  packages/d/dracut/files/0003-Support-an-alternative-bash-build-than-the-default.patch
  packages/d/dracut/files/series
  packages/d/dracut/package.yml
  packages/d/dracut/pspec_x86_64.xml
  packages/n/ncurses/abi_symbols
  packages/n/ncurses/abi_symbols32
  packages/n/ncurses/abi_used_symbols
  packages/n/ncurses/abi_used_symbols32
  packages/n/ncurses/package.yml
  packages/n/ncurses/pspec_x86_64.xml
  packages/r/readline/abi_used_symbols
  packages/r/readline/abi_used_symbols32
  packages/r/readline/package.yml
  packages/r/readline/pspec_x86_64.xml
Labels: Plumbing, Chore

#1653 Plzip initial inclusion (the single-threaded lzip is already in the repo)
  packages/l/lzlib/abi_libs
  packages/l/lzlib/abi_symbols
  packages/l/lzlib/abi_used_libs
  packages/l/lzlib/abi_used_symbols
  packages/l/lzlib/package.yml
  packages/l/lzlib/pspec_x86_64.xml
  packages/p/plzip/abi_libs
  packages/p/plzip/abi_symbols
  packages/p/plzip/abi_used_libs
  packages/p/plzip/abi_used_symbols
  packages/p/plzip/package.yml
  packages/p/plzip/pspec_x86_64.xml
Labels: Feature
