Repository getsolus/packages, pull requests merged in 2024-04, with the labels that each got.

#2149 Update xorg-server and xorg-xwayland
  packages/x/xorg-server/abi_symbols
  packages/x/xorg-server/package.yml
  packages/x/xorg-server/pspec_x86_64.xml
  packages/x/xorg-xwayland/package.yml
  packages/x/xorg-xwayland/pspec_x86_64.xml
Labels: Security

#2150 ypkg: Control which binaries to use via symlinks
  packages/y/ypkg/package.yml
  packages/y/ypkg/pspec_x86_64.xml
Labels: Plumbing, Feature, Tooling

#2120 Convert py2 scripts in common/ to py3
  common/Legacy/Scripts/dep_check.py
  common/Legacy/Scripts/find-old-packages.py
  common/Scripts/dloader.py
  common/Scripts/ep-update.py
  common/Scripts/epcsearch.py
  common/Scripts/find_deps.py
  common/Scripts/gettag.py
  common/Scripts/latent-rebuilds.py
  common/Scripts/pbump.py
  common/Scripts/yauto.py
  common/Scripts/yconvert.py
Labels: Plumbing, Priority: High, Chore, Tooling

#2184 CI/hooks: Bring py3 scripts under test per request
  .github/workflows/script_lint.yml
  common/Scripts/yauto.py
Labels: Plumbing, Feature, Tooling

#2187 fakeroot: Update to 1.34
  packages/f/fakeroot/abi_symbols
  packages/f/fakeroot/abi_symbols32
  packages/f/fakeroot/abi_used_symbols
  packages/f/fakeroot/abi_used_symbols32
  packages/f/fakeroot/monitoring.yml
  packages/f/fakeroot/package.yml
  packages/f/fakeroot/pspec_x86_64.xml
Labels: Plumbing
