Repository getsolus/packages, pull requests merged in 2024-11, with the labels that each got.

#4133 Use %cargo_fetch macro for remaining packages (except zed)
  packages/i/i3-style/abi_used_symbols
  packages/i/i3-style/files/Cargo.lock
  packages/i/i3-style/monitoring.yml
  packages/i/i3-style/package.yml
  packages/i/i3-style/pspec_x86_64.xml
  packages/l/libdovi/files/Cargo.lock
  packages/l/libdovi/package.yml
  packages/l/libdovi/pspec_x86_64.xml
  packages/t/tetrs/files/Cargo.lock
  packages/t/tetrs/package.yml
  packages/t/tetrs/pspec_x86_64.xml
  packages/t/tickrs/abi_used_symbols
  packages/t/tickrs/files/0001-vendored-ssl.patch
  packages/t/tickrs/monitoring.yml
  packages/t/tickrs/package.yml
  packages/t/tickrs/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4005 ibus: Fix build and make stateless
  packages/i/ibus/abi_used_symbols
  packages/i/ibus/files/0001-Stateless-dconf.patch
  packages/i/ibus/files/series
  packages/i/ibus/package.yml
  packages/i/ibus/pspec_x86_64.xml
Labels: Platform Integration, Plumbing, hacktoberfest-accepted

#4200 drive: deprecate
  packages/d/drive/abi_used_libs
  packages/d/drive/abi_used_symbols
  packages/d/drive/package.yml
  packages/d/drive/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: hacktoberfest-accepted

#3826 liburing: Update to 2.7
  packages/l/liburing/abi_libs
  packages/l/liburing/abi_symbols
  packages/l/liburing/package.yml
  packages/l/liburing/pspec_x86_64.xml
Labels: Plumbing, hacktoberfest-accepted

#3811 deprecate: rpi-imager
  packages/r/rpi-imager/MAINTAINERS.md
  packages/r/rpi-imager/abi_used_libs
  packages/r/rpi-imager/abi_used_symbols
  packages/r/rpi-imager/files/0001-appstream-metainfo-Fix-appstream-builder-generation.patch
  packages/r/rpi-imager/monitoring.yml
  packages/r/rpi-imager/package.yml
  packages/r/rpi-imager/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Blocked

#4063 pisi/eopkg: Add versioned FilesDB and LazyDB instances
  packages/e/eopkg/package.yml
  packages/e/eopkg/pspec_x86_64.xml
  packages/p/pisi/pspec.xml
  packages/y/ypkg/package.yml
  packages/y/ypkg/pspec_x86_64.xml
Labels: Platform Integration, Plumbing, hacktoberfest-accepted, Tooling

#3850 solbuild: Drop fakeroot use, use eopkg.bin
  packages/s/solbuild/package.yml
  packages/s/solbuild/pspec_x86_64.xml
Labels: Platform Integration, Plumbing, Tooling

#4142 zenity update
  packages/b/budgie-desktop/abi_used_symbols
  packages/b/budgie-desktop/package.yml
  packages/b/budgie-desktop/pspec_x86_64.xml
  packages/m/marco/files/0001-Update-Zenity-options-for-4.0.patch
  packages/m/marco/files/series
  packages/m/marco/package.yml
  packages/m/marco/pspec_x86_64.xml
  packages/m/mutter/package.yml
  packages/m/mutter/pspec_x86_64.xml
  packages/z/zenity/abi_used_libs
  packages/z/zenity/abi_used_symbols
  packages/z/zenity/package.yml
  packages/z/zenity/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4298 apr: Update to v1.7.5
  packages/a/apr/abi_used_symbols
  packages/a/apr/monitoring.yml
  packages/a/apr/package.yml
  packages/a/apr/pspec_x86_64.xml
Labels: Security

#3431 zsh: fix - do not source bash files and fix build
  packages/z/zsh/files/006-52383-Avoid-incompatible-pointer-types-in-terminfo-g.patch
  packages/z/zsh/files/010-gcc14.patch
  packages/z/zsh/files/series
  packages/z/zsh/files/zprofile
  packages/z/zsh/package.yml
  packages/z/zsh/pspec_x86_64.xml
Labels: Bug, Platform Integration, Plumbing, hacktoberfest-accepted

#3810 Update SELinux
  packages/l/libselinux/abi_symbols
  packages/l/libselinux/abi_used_libs
  packages/l/libselinux/abi_used_symbols
  packages/l/libselinux/package.yml
  packages/l/libselinux/pspec_x86_64.xml
  packages/l/libsepol/abi_symbols
  packages/l/libsepol/abi_used_symbols
  packages/l/libsepol/package.yml
  packages/l/libsepol/pspec_x86_64.xml
Labels: Topic: Platform Integration, Topic: Plumbing

#4129 usysconf-epoch: Only skip if properly merged
  packages/u/usysconf-epoch/files/usr-merge.sh
  packages/u/usysconf-epoch/package.yml
  packages/u/usysconf-epoch/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4359 libmongoc: Update to v1.29.0
  packages/l/libmongoc/abi_libs
  packages/l/libmongoc/abi_symbols
  packages/l/libmongoc/abi_used_libs
  packages/l/libmongoc/abi_used_symbols
  packages/l/libmongoc/monitoring.yml
  packages/l/libmongoc/package.yml
  packages/l/libmongoc/pspec_x86_64.xml
Labels: Type: Security

#4378 opensc: Update to 0.26.0
  packages/o/opensc/abi_libs
  packages/o/opensc/abi_symbols
  packages/o/opensc/abi_used_symbols
  packages/o/opensc/package.yml
  packages/o/opensc/pspec_x86_64.xml
Labels: Type: Security

#4400 github-cli: Update to v2.62.0
  packages/g/github-cli/package.yml
  packages/g/github-cli/pspec_x86_64.xml
Labels: Type: Security

#4417 httpd: Update to v2.4.62
  packages/h/httpd/abi_symbols
  packages/h/httpd/abi_used_symbols
  packages/h/httpd/monitoring.yml
  packages/h/httpd/package.yml
  packages/h/httpd/pspec_x86_64.xml
Labels: Type: Security
