Repository getsolus/packages, pull requests merged in 2024-10, with the labels that each got.

#4046 uniutils: Add at 2.28
  packages/u/uniutils/MAINTAINERS.md
  packages/u/uniutils/abi_used_libs
  packages/u/uniutils/abi_used_symbols
  packages/u/uniutils/files/0001-fix-make.patch
  packages/u/uniutils/package.yml
  packages/u/uniutils/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4044 eqonomize: Update to 1.5.8
  packages/e/eqonomize/abi_used_symbols
  packages/e/eqonomize/package.yml
  packages/e/eqonomize/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4043 distrobox: Update to 1.8.0
  packages/d/distrobox/package.yml
  packages/d/distrobox/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4041 qutebrowser: Update to 3.3.1
  packages/q/qutebrowser/package.yml
  packages/q/qutebrowser/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4012 Update proton-vpn-gtk-app components
  packages/p/proton-vpn-gtk-app/package.yml
  packages/p/proton-vpn-gtk-app/pspec_x86_64.xml
  packages/py/python-proton-core/package.yml
  packages/py/python-proton-core/pspec_x86_64.xml
  packages/py/python-proton-vpn-core-api/package.yml
  packages/py/python-proton-vpn-core-api/pspec_x86_64.xml
  packages/py/python-proton-vpn-killswitch-network-manager-wireguard/package.yml
  packages/py/python-proton-vpn-killswitch-network-manager-wireguard/pspec_x86_64.xml
  packages/py/python-proton-vpn-killswitch-network-manager/package.yml
  packages/py/python-proton-vpn-killswitch-network-manager/pspec_x86_64.xml
  packages/py/python-proton-vpn-network-manager-openvpn/monitoring.yml
  packages/py/python-proton-vpn-network-manager-openvpn/package.yml
  packages/py/python-proton-vpn-network-manager-openvpn/pspec_x86_64.xml
  packages/py/python-proton-vpn-network-manager-wireguard/monitoring.yml
  packages/py/python-proton-vpn-network-manager-wireguard/package.yml
  packages/py/python-proton-vpn-network-manager-wireguard/pspec_x86_64.xml
  packages/py/python-proton-vpn-network-manager/package.yml
  packages/py/python-proton-vpn-network-manager/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: hacktoberfest-accepted

#4017 ibus-bamboo: add at 0.8.4
  packages/i/ibus-bamboo/MAINTAINERS.md
  packages/i/ibus-bamboo/abi_used_libs
  packages/i/ibus-bamboo/abi_used_symbols
  packages/i/ibus-bamboo/package.yml
  packages/i/ibus-bamboo/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4080 github-cli: Update to 2.59.0
  packages/g/github-cli/package.yml
  packages/g/github-cli/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4079 eza: Update to 0.20.3
  packages/e/eza/abi_used_symbols
  packages/e/eza/package.yml
  packages/e/eza/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4070 font-iosevka-ttf: Update to 31.9.1
  packages/f/font-iosevka-ttf/package.yml
  packages/f/font-iosevka-ttf/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4083 podofo:Update to 0.10.4
  packages/c/calibre/abi_used_symbols
  packages/c/calibre/package.yml
  packages/c/calibre/pspec_x86_64.xml
  packages/g/gimagereader/abi_used_symbols
  packages/g/gimagereader/package.yml
  packages/g/gimagereader/pspec_x86_64.xml
  packages/h/horizon-eda/abi_used_symbols
  packages/h/horizon-eda/package.yml
  packages/h/horizon-eda/pspec_x86_64.xml
  packages/k/krename/abi_used_symbols
  packages/k/krename/package.yml
  packages/k/krename/pspec_x86_64.xml
  packages/p/podofo/abi_symbols
  packages/p/podofo/abi_used_symbols
  packages/p/podofo/package.yml
  packages/p/podofo/pspec_x86_64.xml
  packages/s/scribus/package.yml
  packages/s/scribus/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4095 ardour: Update to 8.10
  packages/a/ardour/abi_libs
  packages/a/ardour/abi_symbols
  packages/a/ardour/package.yml
  packages/a/ardour/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4058 streamlink: Update to 6.11.0
  packages/s/streamlink/MAINTAINERS.md
  packages/s/streamlink/monitoring.yml
  packages/s/streamlink/package.yml
  packages/s/streamlink/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#3981 neovim update
  packages/l/libuv/abi_symbols
  packages/l/libuv/abi_used_symbols
  packages/l/libuv/package.yml
  packages/l/libuv/pspec_x86_64.xml
  packages/m/msgpack/abi_symbols
  packages/m/msgpack/monitoring.yml
  packages/m/msgpack/package.yml
  packages/m/msgpack/pspec_x86_64.xml
  packages/n/neovim/abi_symbols
  packages/n/neovim/abi_used_libs
  packages/n/neovim/abi_used_symbols
  packages/n/neovim/package.yml
  packages/n/neovim/pspec_x86_64.xml
Labels: hacktoberfest-accepted, ISO Blocked

#4090 LDC 1.39.0 & Rebuilds
  packages/g/gtkd/abi_used_libs
  packages/g/gtkd/abi_used_symbols
  packages/g/gtkd/package.yml
  packages/g/gtkd/pspec_x86_64.xml
  packages/l/ldc/abi_libs
  packages/l/ldc/abi_symbols
  packages/l/ldc/abi_used_symbols
  packages/l/ldc/package.yml
  packages/l/ldc/pspec_x86_64.xml
  packages/t/tilix/abi_used_libs
  packages/t/tilix/abi_used_symbols
  packages/t/tilix/package.yml
  packages/t/tilix/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4087 geonkick: Update to 3.5.0
  packages/g/geonkick/abi_symbols
  packages/g/geonkick/abi_used_symbols
  packages/g/geonkick/package.yml
  packages/g/geonkick/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4030 yauto: Only scan "configure" files if they're text/plain
  common/Scripts/yauto.py
Labels: hacktoberfest-accepted, Tooling

#4019 common/Hooks: Add support for 'Add at' and '[NFC]' commits
  common/Hooks/prepare-commit-msg.py
Labels: hacktoberfest-accepted, Tooling

#4085 firefox: Enable GNOME Search Provider
  packages/f/firefox/abi_used_symbols
  packages/f/firefox/files/gnome-search-in-open-tabs-1.patch
  packages/f/firefox/files/gnome-search-in-open-tabs-2.patch
  packages/f/firefox/files/org.mozilla.firefox.SearchProvider.service
  packages/f/firefox/files/org.mozilla.firefox.appdata.xml
  packages/f/firefox/files/org.mozilla.firefox.search-provider.ini
  packages/f/firefox/files/prefs.js
  packages/f/firefox/package.yml
  packages/f/firefox/pspec_x86_64.xml
Labels: Feature, hacktoberfest-accepted

#2039 ci/package_checks: Add check for included static libraries
  common/CI/config.yaml
  common/CI/package_checks.py
Labels: Approved, Feature, Tooling, Needs Rebase

#3986 noto-sans-ttf: Update emoji font to 2.047
  packages/n/noto-sans-ttf/package.yml
  packages/n/noto-sans-ttf/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#3996 luajit: Update to 2.1.1727619075
  packages/l/luajit/abi_libs
  packages/l/luajit/abi_symbols
  packages/l/luajit/package.yml
  packages/l/luajit/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4078 Samba 4.19.8 update
  common/CI/config.yaml
  packages/b/budgie-control-center/abi_symbols
  packages/b/budgie-control-center/abi_used_symbols
  packages/b/budgie-control-center/package.yml
  packages/b/budgie-control-center/pspec_x86_64.xml
  packages/f/ffmpeg/package.yml
  packages/f/ffmpeg/pspec_x86_64.xml
  packages/g/gnome-control-center/package.yml
  packages/g/gnome-control-center/pspec_x86_64.xml
  packages/g/gvfs/package.yml
  packages/g/gvfs/pspec_x86_64.xml
  packages/k/kio-extras/package.yml
  packages/k/kio-extras/pspec_x86_64.xml
  packages/l/ldb/abi_symbols
  packages/l/ldb/package.yml
  packages/l/ldb/pspec_x86_64.xml
  packages/m/mpd/abi_used_symbols
  packages/m/mpd/package.yml
  packages/m/mpd/pspec_x86_64.xml
  packages/py/python-pysmbc/package.yml
  packages/py/python-pysmbc/pspec_x86_64.xml
  packages/r/rhythmbox/package.yml
  packages/r/rhythmbox/pspec_x86_64.xml
  packages/s/samba/README.md
  packages/s/samba/abi_symbols
  packages/s/samba/package.yml
  packages/s/samba/pspec_x86_64.xml
  packages/v/vlc/abi_used_symbols
  packages/v/vlc/package.yml
  packages/v/vlc/pspec_x86_64.xml
Labels: hacktoberfest-accepted, Blocked

#3974 postgresql: Update to 17.0
  packages/p/postgresql/abi_libs
  packages/p/postgresql/abi_symbols
  packages/p/postgresql/abi_used_symbols
  packages/p/postgresql/package.yml
  packages/p/postgresql/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4062 lact: Update to 0.5.6
  packages/l/lact/abi_used_symbols
  packages/l/lact/files/group-priority.patch
  packages/l/lact/package.yml
  packages/l/lact/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4144 sof-firmware: update to 2.11.1
  packages/s/sof-firmware/package.yml
  packages/s/sof-firmware/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#3608 Add template for reporting problems with packages
  .github/ISSUE_TEMPLATE/report-packaging-problems.yml
Labels: Chore, hacktoberfest-accepted, Tooling

#4053 gpxsee: Migrate to QT6
  packages/g/gpxsee/abi_used_libs
  packages/g/gpxsee/abi_used_symbols
  packages/g/gpxsee/package.yml
  packages/g/gpxsee/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4166 syncthing: Update to v1.28.0
  packages/s/syncthing/package.yml
  packages/s/syncthing/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#4086 os-release: Manage os-release outside of baselayout
  packages/o/os-release/files/os-release
  packages/o/os-release/files/os-release.tmpfiles
  packages/o/os-release/files/solus-release
  packages/o/os-release/package.yml
  packages/o/os-release/pspec_x86_64.xml
  packages/s/systemd/files/patches/downstream/0015-Remove-etc-os-release-from-tmpfiles.patch
  packages/s/systemd/files/series
  packages/s/systemd/package.yml
  packages/s/systemd/pspec_x86_64.xml
Labels: Platform Integration, Plumbing, hacktoberfest-accepted, Needs Rebase

#4071 Update hyprland
  packages/a/aquamarine/abi_symbols
  packages/a/aquamarine/abi_used_symbols
  packages/a/aquamarine/package.yml
  packages/a/aquamarine/pspec_x86_64.xml
  packages/h/hyprcursor/abi_used_symbols
  packages/h/hyprcursor/package.yml
  packages/h/hyprcursor/pspec_x86_64.xml
  packages/h/hyprland/abi_symbols
  packages/h/hyprland/abi_used_symbols
  packages/h/hyprland/package.yml
  packages/h/hyprland/pspec_x86_64.xml
  packages/h/hyprlang/abi_symbols
  packages/h/hyprlang/abi_used_libs
  packages/h/hyprlang/abi_used_symbols
  packages/h/hyprlang/package.yml
  packages/h/hyprlang/pspec_x86_64.xml
  packages/h/hyprutils/abi_symbols
  packages/h/hyprutils/abi_used_symbols
  packages/h/hyprutils/package.yml
  packages/h/hyprutils/pspec_x86_64.xml
  packages/h/hyprwayland-scanner/package.yml
  packages/h/hyprwayland-scanner/pspec_x86_64.xml
  packages/x/xdg-desktop-portal-hyprland/abi_libs
  packages/x/xdg-desktop-portal-hyprland/abi_symbols
  packages/x/xdg-desktop-portal-hyprland/abi_used_symbols
  packages/x/xdg-desktop-portal-hyprland/package.yml
  packages/x/xdg-desktop-portal-hyprland/pspec_x86_64.xml
Labels: hacktoberfest-accepted

#3985 nitrogen: deprecate
  packages/n/nitrogen/abi_used_libs
  packages/n/nitrogen/abi_used_symbols
  packages/n/nitrogen/monitoring.yml
  packages/n/nitrogen/package.yml
  packages/n/nitrogen/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: hacktoberfest-accepted

#4156 libarchive: fix dependencies
  packages/l/libarchive/package.yml
  packages/l/libarchive/pspec_x86_64.xml
Labels: hacktoberfest-accepted
