Repository getsolus/packages, pull requests merged in 2024-06, with the labels that each got.

#2904 packages: Remove gradio
  packages/g/gradio/abi_used_libs
  packages/g/gradio/abi_used_symbols
  packages/g/gradio/package.yml
  packages/g/gradio/pspec_x86_64.xml
Labels: Deprecation or removal from repository

#2903 packages: Remove wxwidgets30
  packages/w/wxwidgets30/abi_used_libs
  packages/w/wxwidgets30/abi_used_symbols
  packages/w/wxwidgets30/files/Fix-default-enable-mediactrl.patch
  packages/w/wxwidgets30/files/Warn-on-ABI-mismatch.patch
  packages/w/wxwidgets30/package.yml
  packages/w/wxwidgets30/pspec_x86_64.xml
Labels: Deprecation or removal from repository

#2906 packages: Remove powerlevel9k
  packages/p/powerlevel9k/package.yml
  packages/p/powerlevel9k/pspec_x86_64.xml
Labels: Deprecation or removal from repository

#2169 eopkg: Add unified eopkg py3/nuitka'd package
  packages/e/eopkg/abi_used_libs
  packages/e/eopkg/abi_used_symbols
  packages/e/eopkg/package.yml
  packages/e/eopkg/pspec_x86_64.xml
  packages/e/eopkg4-bin/README.md
  packages/e/eopkg4-bin/files/0001-Use-different-database.patch
  packages/e/eopkg4-bin/package.yml
  packages/e/eopkg4-bin/pspec_x86_64.xml
  packages/py/python-eopkg/files/0001-Add-extended-attributes-support-from-base64-encoded-.patch
  packages/py/python-eopkg/package.yml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Plumbing, Priority: High, Feature, Tooling

#2894 antibody: Deprecate
  packages/a/antibody/MAINTAINERS.md
  packages/a/antibody/abi_used_libs
  packages/a/antibody/abi_used_symbols
  packages/a/antibody/package.yml
  packages/a/antibody/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Deprecation or removal from repository

#2860 Remove redkite from geonkick's builddeps and deprecate it
  packages/g/geonkick/package.yml
  packages/g/geonkick/pspec_x86_64.xml
  packages/r/redkite/abi_used_libs
  packages/r/redkite/abi_used_symbols
  packages/r/redkite/package.yml
  packages/r/redkite/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Deprecation or removal from repository

#2933 mbedtls: Update to 2.28.2
  packages/m/mbedtls/abi_symbols
  packages/m/mbedtls/files/revert-unconditional-third-party.patch
  packages/m/mbedtls/package.yml
  packages/m/mbedtls/pspec_x86_64.xml
Labels: Security

#3037 Taskfile: Improve ergonomics by adding aliases
  Taskfile.yml
Labels: Feature

#3057 python2-ordered-set: Add at 3.1.1
  packages/py/python2-ordered-set/package.yml
  packages/py/python2-ordered-set/pspec_x86_64.xml
Labels: Plumbing, Approved, Priority: High, Feature, Tooling

#3043 Taskfile: Use more uniform syntax and tweak output
  Taskfile.yml
Labels: Chore

#3119 eopkg: sync packagekit backend w/ git for eopkg.bin
  packages/e/eopkg/package.yml
  packages/e/eopkg/pspec_x86_64.xml
Labels: Bug

#3138 eopkg/pisi: Order baselayout first, don't reorder eopkg
  packages/e/eopkg/package.yml
  packages/e/eopkg/pspec_x86_64.xml
  packages/p/pisi/files/baselayout-first-no-eopkg-reordering.patch
  packages/p/pisi/pspec.xml
Labels: Plumbing, Priority: High
