Repository getsolus/packages, pull requests merged in 2024-05, with the labels that each got.

#2279 samba: Add autobuild.yml files for dep resolution
  common/autobuild-ignore-doxygen.yml
  common/autobuild-ignore-python-pytest.yml
  packages/l/llvm-bolt/autobuild.yml
  packages/l/llvm/autobuild.yml
  packages/m/mesalib/autobuild.yml
  packages/o/openjdk-17/autobuild.yml
  packages/p/pulseaudio/autobuild.yml
  packages/py/python-chardet/autobuild.yml
  packages/py/python-jinja/autobuild.yml
  packages/py/python-requests/autobuild.yml
  packages/py/python-wheel/autobuild.yml
  packages/t/tpm2-tss/autobuild.yml
Labels: Platform Integration, Feature, Tooling

#2482 Xfce additions
  packages/x/xfce4-battery-plugin/abi_libs
  packages/x/xfce4-battery-plugin/abi_symbols
  packages/x/xfce4-battery-plugin/abi_used_libs
  packages/x/xfce4-battery-plugin/abi_used_symbols
  packages/x/xfce4-battery-plugin/monitoring.yml
  packages/x/xfce4-battery-plugin/package.yml
  packages/x/xfce4-battery-plugin/pspec_x86_64.xml
  packages/x/xfce4-clipman-plugin/abi_libs
  packages/x/xfce4-clipman-plugin/abi_symbols
  packages/x/xfce4-clipman-plugin/abi_used_libs
  packages/x/xfce4-clipman-plugin/abi_used_symbols
  packages/x/xfce4-clipman-plugin/monitoring.yml
  packages/x/xfce4-clipman-plugin/package.yml
  packages/x/xfce4-clipman-plugin/pspec_x86_64.xml
Labels: Xfce, Priority: High, Feature

#2676 Taskfile: List *.eopkg files in tree before removal
  Taskfile.yml
Labels: Feature

#847 blender: Enable CUDA and OptiX support
  packages/b/blender/abi_used_symbols
  packages/b/blender/package.yml
  packages/b/blender/pspec_x86_64.xml
Labels: Feature
