Repository getsolus/packages, pull requests merged in 2025-03, with the labels that each got.

#5172 nvidia-glx-driver: Update to v570.124.04
  packages/n/nvidia-glx-driver/abi_libs
  packages/n/nvidia-glx-driver/abi_libs32
  packages/n/nvidia-glx-driver/abi_symbols
  packages/n/nvidia-glx-driver/abi_symbols32
  packages/n/nvidia-glx-driver/abi_used_symbols
  packages/n/nvidia-glx-driver/abi_used_symbols32
  packages/n/nvidia-glx-driver/files/cmdline-nvidia.conf
  packages/n/nvidia-glx-driver/files/make-modeset-fbdev-default.diff
  packages/n/nvidia-glx-driver/package.yml
  packages/n/nvidia-glx-driver/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5209 authenticator: Add at v4.5.0
  packages/a/authenticator/MAINTAINERS.md
  packages/a/authenticator/abi_used_libs
  packages/a/authenticator/abi_used_symbols
  packages/a/authenticator/monitoring.yaml
  packages/a/authenticator/package.yml
  packages/a/authenticator/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5208 Add Fragments
  packages/f/fragments/MAINTAINERS.md
  packages/f/fragments/abi_used_libs
  packages/f/fragments/abi_used_symbols
  packages/f/fragments/monitoring.yaml
  packages/f/fragments/package.yml
  packages/f/fragments/pspec_x86_64.xml
  packages/t/transmission/abi_used_symbols
  packages/t/transmission/package.yml
  packages/t/transmission/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5211 Hypr Update
  packages/a/aquamarine/abi_used_libs
  packages/a/aquamarine/abi_used_symbols
  packages/a/aquamarine/package.yml
  packages/a/aquamarine/pspec_x86_64.xml
  packages/g/glaze/monitoring.yaml
  packages/g/glaze/package.yml
  packages/g/glaze/pspec_x86_64.xml
  packages/h/hyprcursor/package.yml
  packages/h/hyprcursor/pspec_x86_64.xml
  packages/h/hyprgraphics/abi_symbols
  packages/h/hyprgraphics/abi_used_libs
  packages/h/hyprgraphics/abi_used_symbols
  packages/h/hyprgraphics/package.yml
  packages/h/hyprgraphics/pspec_x86_64.xml
  packages/h/hypridle/abi_used_libs
  packages/h/hypridle/abi_used_symbols
  packages/h/hypridle/package.yml
  packages/h/hypridle/pspec_x86_64.xml
  packages/h/hyprland-protocols/package.yml
  packages/h/hyprland-protocols/pspec_x86_64.xml
  packages/h/hyprland-qt-support/package.yml
  packages/h/hyprland-qt-support/pspec_x86_64.xml
  packages/h/hyprland-qutils/abi_used_libs
  packages/h/hyprland-qutils/abi_used_symbols
  packages/h/hyprland-qutils/package.yml
  packages/h/hyprland-qutils/pspec_x86_64.xml
  packages/h/hyprland/README.md
  packages/h/hyprland/abi_symbols
  packages/h/hyprland/abi_used_libs
  packages/h/hyprland/abi_used_symbols
  packages/h/hyprland/package.yml
  packages/h/hyprland/pspec_x86_64.xml
  packages/h/hyprlang/abi_used_libs
  packages/h/hyprlang/abi_used_symbols
  packages/h/hyprlang/package.yml
  packages/h/hyprlang/pspec_x86_64.xml
  packages/h/hyprlock/abi_libs
  packages/h/hyprlock/abi_symbols
  packages/h/hyprlock/abi_used_libs
  packages/h/hyprlock/abi_used_symbols
  packages/h/hyprlock/package.yml
  packages/h/hyprlock/pspec_x86_64.xml
  packages/h/hyprpaper/abi_used_libs
  packages/h/hyprpaper/abi_used_symbols
  packages/h/hyprpaper/package.yml
  packages/h/hyprpaper/pspec_x86_64.xml
  packages/h/hyprutils/abi_libs
  packages/h/hyprutils/abi_symbols
  packages/h/hyprutils/abi_used_symbols
  packages/h/hyprutils/package.yml
  packages/h/hyprutils/pspec_x86_64.xml
  packages/x/xdg-desktop-portal-hyprland/abi_used_libs
  packages/x/xdg-desktop-portal-hyprland/abi_used_symbols
  packages/x/xdg-desktop-portal-hyprland/package.yml
  packages/x/xdg-desktop-portal-hyprland/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5212 Initial inclusion of Mir and Miriway
  packages/m/mir/MAINTAINERS.md
  packages/m/mir/abi_libs
  packages/m/mir/abi_symbols
  packages/m/mir/abi_used_libs
  packages/m/mir/abi_used_symbols
  packages/m/mir/monitoring.yaml
  packages/m/mir/package.yml
  packages/m/mir/pspec_x86_64.xml
  packages/m/miriway/MAINTAINERS.md
  packages/m/miriway/abi_used_libs
  packages/m/miriway/abi_used_symbols
  packages/m/miriway/monitoring.yaml
  packages/m/miriway/package.yml
  packages/m/miriway/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5251 firefox: Use beacondb geolocation
  packages/f/firefox/files/prefs.js
  packages/f/firefox/package.yml
  packages/f/firefox/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5287 Gimp 3.0
  packages/b/babl/abi_libs
  packages/b/babl/abi_symbols
  packages/b/babl/abi_used_symbols
  packages/b/babl/package.yml
  packages/b/babl/pspec_x86_64.xml
  packages/g/gegl/abi_symbols
  packages/g/gegl/abi_used_symbols
  packages/g/gegl/package.yml
  packages/g/gegl/pspec_x86_64.xml
  packages/g/gimp/abi_libs
  packages/g/gimp/abi_symbols
  packages/g/gimp/abi_used_libs
  packages/g/gimp/abi_used_symbols
  packages/g/gimp/package.yml
  packages/g/gimp/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5288 mbedtls: Update to v2.28.10
  packages/m/mbedtls/abi_symbols
  packages/m/mbedtls/files/0001-Fix-calloc-argument-order.patch
  packages/m/mbedtls/package.yml
  packages/m/mbedtls/pspec_x86_64.xml
Labels: Type: Security

#5302 Hyprland update
  packages/a/aquamarine/abi_libs
  packages/a/aquamarine/abi_symbols
  packages/a/aquamarine/abi_used_symbols
  packages/a/aquamarine/package.yml
  packages/a/aquamarine/pspec_x86_64.xml
  packages/g/glaze/package.yml
  packages/g/glaze/pspec_x86_64.xml
  packages/h/hyprcursor/abi_symbols
  packages/h/hyprcursor/abi_used_libs
  packages/h/hyprcursor/abi_used_symbols
  packages/h/hyprcursor/package.yml
  packages/h/hyprcursor/pspec_x86_64.xml
  packages/h/hyprland/abi_symbols
  packages/h/hyprland/abi_used_libs
  packages/h/hyprland/abi_used_symbols
  packages/h/hyprland/package.yml
  packages/h/hyprland/pspec_x86_64.xml
  packages/h/hyprutils/package.yml
  packages/h/hyprutils/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5298 Xfce updates
  packages/l/libxfce4ui/abi_used_symbols
  packages/l/libxfce4ui/monitoring.yaml
  packages/l/libxfce4ui/package.yml
  packages/l/libxfce4ui/pspec_x86_64.xml
  packages/l/libxfce4util/abi_used_symbols
  packages/l/libxfce4util/monitoring.yaml
  packages/l/libxfce4util/package.yml
  packages/l/libxfce4util/pspec_x86_64.xml
  packages/r/ristretto/MAINTAINERS.md
  packages/r/ristretto/abi_used_libs
  packages/r/ristretto/abi_used_symbols
  packages/r/ristretto/package.yml
  packages/r/ristretto/pspec_x86_64.xml
  packages/x/xfce4-panel/abi_symbols
  packages/x/xfce4-panel/abi_used_symbols
  packages/x/xfce4-panel/monitoring.yaml
  packages/x/xfce4-panel/package.yml
  packages/x/xfce4-panel/pspec_x86_64.xml
  packages/x/xfce4-session/abi_symbols
  packages/x/xfce4-session/abi_used_symbols
  packages/x/xfce4-session/files/0001-labwc-Set-snapping-range-to-10.patch
  packages/x/xfce4-session/files/0001-labwc-Use-Breeze-cursors.patch
  packages/x/xfce4-session/files/0001-scripts-xinitrc-Source-vendered-and-system-xinitrc-s.patch
  packages/x/xfce4-session/monitoring.yaml
  packages/x/xfce4-session/package.yml
  packages/x/xfce4-session/pspec_x86_64.xml
  packages/x/xfce4-terminal/MAINTAINERS.md
  packages/x/xfce4-terminal/abi_used_symbols
  packages/x/xfce4-terminal/package.yml
  packages/x/xfce4-terminal/pspec_x86_64.xml
Labels: Edition: Xfce, Topic: Sync Notes

#5306 deskflow: Add at v1.20.1
  packages/d/deskflow/MAINTAINERS.md
  packages/d/deskflow/abi_used_libs
  packages/d/deskflow/abi_used_symbols
  packages/d/deskflow/files/disable-update-check.patch
  packages/d/deskflow/monitoring.yaml
  packages/d/deskflow/package.yml
  packages/d/deskflow/pspec_x86_64.xml
Labels: Topic: Sync Notes
