Repository getsolus/packages, pull requests merged in 2025-02, with the labels that each got.

#4948 nvidia-beta-driver: Update to v570.86.16
  packages/n/nvidia-beta-driver/abi_libs
  packages/n/nvidia-beta-driver/abi_libs32
  packages/n/nvidia-beta-driver/abi_symbols
  packages/n/nvidia-beta-driver/abi_symbols32
  packages/n/nvidia-beta-driver/abi_used_symbols
  packages/n/nvidia-beta-driver/abi_used_symbols32
  packages/n/nvidia-beta-driver/files/cmdline-nvidia.conf
  packages/n/nvidia-beta-driver/files/make-modeset-fbdev-default.diff
  packages/n/nvidia-beta-driver/package.yml
  packages/n/nvidia-beta-driver/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4965 GNOME 47.4
  packages/b/bash-completion/package.yml
  packages/b/bash-completion/pspec_x86_64.xml
  packages/g/gnome-color-manager/abi_used_symbols
  packages/g/gnome-color-manager/package.yml
  packages/g/gnome-color-manager/pspec_x86_64.xml
  packages/g/gnome-connections/abi_used_symbols
  packages/g/gnome-connections/package.yml
  packages/g/gnome-connections/pspec_x86_64.xml
  packages/g/gnome-control-center/abi_symbols
  packages/g/gnome-control-center/abi_used_symbols
  packages/g/gnome-control-center/package.yml
  packages/g/gnome-control-center/pspec_x86_64.xml
  packages/g/gnome-maps/package.yml
  packages/g/gnome-maps/pspec_x86_64.xml
  packages/g/gnome-system-monitor/abi_used_symbols
  packages/g/gnome-system-monitor/package.yml
  packages/g/gnome-system-monitor/pspec_x86_64.xml
  packages/g/gnome-text-editor/abi_used_symbols
  packages/g/gnome-text-editor/package.yml
  packages/g/gnome-text-editor/pspec_x86_64.xml
  packages/g/gnome-web/abi_symbols
  packages/g/gnome-web/abi_used_symbols
  packages/g/gnome-web/package.yml
  packages/g/gnome-web/pspec_x86_64.xml
  packages/g/gupnp-av/files/Remove-deprecates-xmlRecoverMemory.patch
  packages/g/gupnp-av/package.yml
  packages/g/gupnp-av/pspec_x86_64.xml
  packages/g/gupnp/abi_symbols
  packages/g/gupnp/abi_used_symbols
  packages/g/gupnp/package.yml
  packages/g/gupnp/pspec_x86_64.xml
  packages/l/libadwaita/abi_used_symbols
  packages/l/libadwaita/package.yml
  packages/l/libadwaita/pspec_x86_64.xml
  packages/l/libgee/abi_used_symbols
  packages/l/libgee/package.yml
  packages/l/libgee/pspec_x86_64.xml
  packages/l/libsecret/abi_symbols
  packages/l/libsecret/package.yml
  packages/l/libsecret/pspec_x86_64.xml
  packages/l/libshumate/package.yml
  packages/l/libshumate/pspec_x86_64.xml
  packages/l/libvte/package.yml
  packages/l/libvte/pspec_x86_64.xml
  packages/l/loupe/package.yml
  packages/l/loupe/pspec_x86_64.xml
  packages/x/xdg-desktop-portal-gnome/package.yml
  packages/x/xdg-desktop-portal-gnome/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5002 rtmpdump: Update to v2.6
  packages/r/rtmpdump/package.yml
  packages/r/rtmpdump/pspec_x86_64.xml
Labels: Type: Security, Topic: Sync Notes

#5031 flatpak: Use /usr/flatpak/remotes.d to enable Flathub by default
  packages/f/flatpak/files/flathub.flatpakrepo
  packages/f/flatpak/files/flatpak-enable-flathub.service
  packages/f/flatpak/package.yml
  packages/f/flatpak/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5054 ibus: Update to v1.5.31
  packages/i/ibus/abi_symbols
  packages/i/ibus/abi_used_symbols
  packages/i/ibus/monitoring.yaml
  packages/i/ibus/package.yml
  packages/i/ibus/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5053 xfce4-whiskermenu-plugin: Update to v2.9.1
  packages/x/xfce4-whiskermenu-plugin/MAINTAINERS.md
  packages/x/xfce4-whiskermenu-plugin/abi_used_libs
  packages/x/xfce4-whiskermenu-plugin/abi_used_symbols
  packages/x/xfce4-whiskermenu-plugin/files/0001-Fix-menu-not-shown-on-correct-monitor.patch
  packages/x/xfce4-whiskermenu-plugin/package.yml
  packages/x/xfce4-whiskermenu-plugin/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5059 deno: Update to v2.1.10
  packages/d/deno/abi_symbols
  packages/d/deno/abi_used_symbols
  packages/d/deno/package.yml
  packages/d/deno/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5078 krusader: Update to v2.9.0
  packages/k/krusader/abi_symbols
  packages/k/krusader/abi_used_libs
  packages/k/krusader/abi_used_symbols
  packages/k/krusader/package.yml
  packages/k/krusader/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5049 gammastep: Add at v2.0.9
  packages/g/gammastep/MAINTAINERS.md
  packages/g/gammastep/abi_used_libs
  packages/g/gammastep/abi_used_symbols
  packages/g/gammastep/monitoring.yaml
  packages/g/gammastep/package.yml
  packages/g/gammastep/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5060 sway & labwc: decouple rundeps
  packages/l/labwc/package.yml
  packages/l/labwc/pspec_x86_64.xml
  packages/s/sway/package.yml
  packages/s/sway/pspec_x86_64.xml
  packages/x/xdg-desktop-portal-wlr/abi_used_symbols
  packages/x/xdg-desktop-portal-wlr/package.yml
  packages/x/xdg-desktop-portal-wlr/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5062 opentofu: Add at v1.9.0
  packages/o/opentofu/abi_used_libs
  packages/o/opentofu/abi_used_symbols
  packages/o/opentofu/files/tofu.bash
  packages/o/opentofu/files/tofu.fish
  packages/o/opentofu/files/tofu.zsh
  packages/o/opentofu/monitoring.yaml
  packages/o/opentofu/package.yml
  packages/o/opentofu/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5091 update budgie xfce branding
  packages/b/budgie-desktop-branding/package.yml
  packages/b/budgie-desktop-branding/pspec_x86_64.xml
  packages/x/xfce4-desktop-branding/package.yml
  packages/x/xfce4-desktop-branding/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5090 github-cli: Update to v2.67.0
  packages/g/github-cli/package.yml
  packages/g/github-cli/pspec_x86_64.xml
Labels: Type: Security

#5087 zenergy: Add at v1.0
  packages/z/zenergy/monitoring.yaml
  packages/z/zenergy/package.yml
  packages/z/zenergy/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4553 repo-wide: Remove re-licensed HashiCorp products
  packages/c/consul/package.yml
  packages/c/consul/pspec_x86_64.xml
  packages/n/nomad/abi_used_libs
  packages/n/nomad/abi_used_symbols
  packages/n/nomad/package.yml
  packages/n/nomad/pspec_x86_64.xml
  packages/t/terraform/MAINTAINERS.md
  packages/t/terraform/abi_used_libs
  packages/t/terraform/abi_used_symbols
  packages/t/terraform/package.yml
  packages/t/terraform/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Type: Security, Priority: Normal, Topic: Sync Notes

#4952 adwaita-fonts: Add at v48.2
  packages/a/adwaita-fonts/files/adwaita-fonts.metainfo.xml
  packages/a/adwaita-fonts/monitoring.yaml
  packages/a/adwaita-fonts/package.yml
  packages/a/adwaita-fonts/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5133 socat: Update to v1.8.0.3
  packages/s/socat/abi_used_symbols
  packages/s/socat/monitoring.yaml
  packages/s/socat/package.yml
  packages/s/socat/pspec_x86_64.xml
Labels: Type: Security

#4920 gpu-screen-recorder: Add at v5.1.0
  packages/g/gpu-screen-recorder-gtk/MAINTAINERS.md
  packages/g/gpu-screen-recorder-gtk/abi_used_libs
  packages/g/gpu-screen-recorder-gtk/abi_used_symbols
  packages/g/gpu-screen-recorder-gtk/package.yml
  packages/g/gpu-screen-recorder-gtk/pspec_x86_64.xml
  packages/g/gpu-screen-recorder/MAINTAINERS.md
  packages/g/gpu-screen-recorder/abi_libs
  packages/g/gpu-screen-recorder/abi_symbols
  packages/g/gpu-screen-recorder/abi_used_libs
  packages/g/gpu-screen-recorder/abi_used_symbols
  packages/g/gpu-screen-recorder/package.yml
  packages/g/gpu-screen-recorder/pspec_x86_64.xml
Labels: Topic: Sync Notes
