Repository getsolus/packages, pull requests merged in 2025-04, with the labels that each got.

#4783 opensnitch: Add at v1.6.8
  packages/o/opensnitch/MAINTAINERS.md
  packages/o/opensnitch/abi_used_libs
  packages/o/opensnitch/abi_used_symbols
  packages/o/opensnitch/files/add-generated-protobuf-files.patch
  packages/o/opensnitch/files/correct-systemd-service.patch
  packages/o/opensnitch/files/opensnitch.sysusers
  packages/o/opensnitch/files/opensnitch.tmpfile
  packages/o/opensnitch/files/update-config.patch
  packages/o/opensnitch/files/update-socket.patch
  packages/o/opensnitch/files/use-system-python.patch
  packages/o/opensnitch/monitoring.yaml
  packages/o/opensnitch/package.yml
  packages/o/opensnitch/pspec_x86_64.xml
  packages/py/python-qt-material/monitoring.yaml
  packages/py/python-qt-material/package.yml
  packages/py/python-qt-material/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4973 showtime: Add at v48.0
  packages/s/showtime/monitoring.yaml
  packages/s/showtime/package.yml
  packages/s/showtime/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5377 drm_info: Add at v2.7.0
  packages/d/drm_info/abi_used_libs
  packages/d/drm_info/abi_used_symbols
  packages/d/drm_info/monitoring.yaml
  packages/d/drm_info/package.yml
  packages/d/drm_info/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5178 ibus: Update to v1.5.32
  packages/i/ibus/abi_symbols
  packages/i/ibus/abi_used_symbols
  packages/i/ibus/files/segv-bus-proxy.patch
  packages/i/ibus/files/series
  packages/i/ibus/package.yml
  packages/i/ibus/pspec_x86_64.xml
Labels: Blocked: Upstream

#5513 xrdp-xfce4-integration: Use the correct binary in the startwm.sh
  packages/x/xrdp-xfce4-integration/files/startwm.sh
  packages/x/xrdp-xfce4-integration/package.yml
  packages/x/xrdp-xfce4-integration/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5505 nvidia-glx-driver: Update to v570.144
  packages/n/nvidia-glx-driver/abi_libs
  packages/n/nvidia-glx-driver/abi_libs32
  packages/n/nvidia-glx-driver/abi_symbols
  packages/n/nvidia-glx-driver/abi_symbols32
  packages/n/nvidia-glx-driver/package.yml
  packages/n/nvidia-glx-driver/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5515 valkey: Update to v8.1.1
  packages/v/valkey/abi_symbols
  packages/v/valkey/dump.rdb
  packages/v/valkey/package.yml
  packages/v/valkey/pspec_x86_64.xml
Labels: Type: Security, Topic: Sync Notes

#5520 steam: Update to v1.0.0.83
  packages/s/steam/package.yml
  packages/s/steam/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5558 scd2html: Add at v1.0.0
  packages/s/scd2html/MAINTAINERS.md
  packages/s/scd2html/monitoring.yml
  packages/s/scd2html/package.yml
  packages/s/scd2html/pspec_x86_64.xml
Labels: Topic: Sync Notes
