Repository getsolus/packages, pull requests merged in 2025-06, with the labels that each got.

#5749 cmatrix: packaging fixes
  packages/c/cmatrix/abi_used_symbols
  packages/c/cmatrix/monitoring.yaml
  packages/c/cmatrix/package.yml
  packages/c/cmatrix/pspec_x86_64.xml
Labels: Blocked: Other

#5745 octave: Update to v10.2.0
  packages/o/octave/abi_symbols
  packages/o/octave/abi_used_symbols
  packages/o/octave/package.yml
  packages/o/octave/pspec_x86_64.xml
Labels: Blocked: Other

#5737 helix: Add application info and completions
  packages/h/helix/files/hx
  packages/h/helix/package.yml
  packages/h/helix/pspec_x86_64.xml
Labels: Blocked: Other

#5722 usbutils: Update to v018
  packages/u/usbutils/abi_used_symbols
  packages/u/usbutils/files/usbreset.patch
  packages/u/usbutils/package.yml
  packages/u/usbutils/pspec_x86_64.xml
Labels: Blocked: Other

#5723 Add openvpn3
  packages/g/gdbuspp/MAINTAINERS.md
  packages/g/gdbuspp/abi_libs
  packages/g/gdbuspp/abi_symbols
  packages/g/gdbuspp/abi_used_libs
  packages/g/gdbuspp/abi_used_symbols
  packages/g/gdbuspp/monitoring.yaml
  packages/g/gdbuspp/package.yml
  packages/g/gdbuspp/pspec_x86_64.xml
  packages/o/openvpn3/MAINTAINERS.md
  packages/o/openvpn3/abi_used_libs
  packages/o/openvpn3/abi_used_symbols
  packages/o/openvpn3/files/0001-build-Fix-incorrect-OPENVPN_USERNAME-in-D-Bus-autost.patch
  packages/o/openvpn3/files/0002-build-Prepare-for-bumping-the-required-C-standard-ve.patch
  packages/o/openvpn3/files/0003-tests-Upgrade-to-googletest-1.17.0-1.patch
  packages/o/openvpn3/files/0004-addon-aws-Prepare-for-bumping-the-required-C-standar.patch
  packages/o/openvpn3/files/0005-Use-system-gtest.patch
  packages/o/openvpn3/files/series
  packages/o/openvpn3/files/sysusers.conf
  packages/o/openvpn3/files/tmpfiles.conf
  packages/o/openvpn3/monitoring.yaml
  packages/o/openvpn3/package.yml
  packages/o/openvpn3/pspec_x86_64.xml
Labels: Blocked: Other, Topic: Sync Notes

#5734 cereal: change homepage
  packages/c/cereal/package.yml
  packages/c/cereal/pspec_x86_64.xml
Labels: Blocked: Other

#5736 watchexec: Update to v2.3.2
  packages/w/watchexec/abi_used_symbols
  packages/w/watchexec/package.yml
  packages/w/watchexec/pspec_x86_64.xml
Labels: Blocked: Other

#5738 rebar3: Update to v3.25.0
  packages/r/rebar3/package.yml
  packages/r/rebar3/pspec_x86_64.xml
Labels: Blocked: Other

#5739 gleam: Update to v1.11.0
  packages/g/gleam/abi_used_symbols
  packages/g/gleam/package.yml
  packages/g/gleam/pspec_x86_64.xml
Labels: Blocked: Other

#5742 meson: Install autocompletions
  packages/m/meson/package.yml
  packages/m/meson/pspec_x86_64.xml
Labels: Blocked: Other

#5781 gnome-software: Enable show console applications
  packages/g/gnome-software/files/0001-Show-console-apps.patch
  packages/g/gnome-software/package.yml
  packages/g/gnome-software/pspec_x86_64.xml
Labels: Topic: Sync Notes

#5828 valkey: Update to v8.1.2
  packages/v/valkey/abi_symbols
  packages/v/valkey/abi_used_symbols
  packages/v/valkey/dump.rdb
  packages/v/valkey/package.yml
  packages/v/valkey/pspec_x86_64.xml
Labels: Type: Security

#5829 dool: add at version 1.3.4
  packages/d/dool/monitoring.yaml
  packages/d/dool/package.yml
  packages/d/dool/pspec_x86_64.xml
  packages/d/dstat/files/0001-Fix-bug-when-specifiying-delay.patch
  packages/d/dstat/files/0001-Use-python3-and-avoid-deprecation-warnings.patch
  packages/d/dstat/files/series
  packages/d/dstat/package.yml
  packages/d/dstat/pspec_x86_64.xml
  repo_data/distribution.xml
  repo_data/distribution.xml.in
Labels: Topic: Sync Notes

#5836 httrack: Update to v3.49.6
  packages/h/httrack/abi_used_symbols
  packages/h/httrack/package.yml
  packages/h/httrack/pspec_x86_64.xml
Labels: Type: Security

#5873 jq: Update to v1.8.0
  packages/j/jq/abi_symbols
  packages/j/jq/abi_used_symbols
  packages/j/jq/package.yml
  packages/j/jq/pspec_x86_64.xml
Labels: Type: Security

#5820 pisi: Make `eopkg.bin` the default
  packages/p/pisi/actions.py
  packages/p/pisi/pspec.xml
Labels: Topic: Sync Notes
