Repository getsolus/packages, pull requests merged in 2025-01, with the labels that each got.

#4713 dotnet: Update to 8.0.11
  common/CI/config.yaml
  packages/d/dotnet/files/0002-solus-dac-fix.patch
  packages/d/dotnet/files/release.json
  packages/d/dotnet/package.yml
  packages/d/dotnet/pspec_x86_64.xml
Labels: Type: Security, Topic: Sync Notes

#4740 acpica-unix: Update to v20241212
  packages/a/acpica-unix/package.yml
  packages/a/acpica-unix/pspec_x86_64.xml
Labels: Type: Security

#4789 valkey: Update to v8.0.2
  packages/v/valkey/abi_symbols
  packages/v/valkey/package.yml
  packages/v/valkey/pspec_x86_64.xml
Labels: Type: Security, Topic: Sync Notes

#4791 codelite: Update to v18.1.0
  packages/c/codelite/abi_libs
  packages/c/codelite/abi_symbols
  packages/c/codelite/abi_used_libs
  packages/c/codelite/abi_used_symbols
  packages/c/codelite/files/3428.patch
  packages/c/codelite/files/fix-wxwidgets-build.patch
  packages/c/codelite/package.yml
  packages/c/codelite/pspec_x86_64.xml
Labels: Topic: Sync Notes

#4857 gnome-bluetooth: fix homepage
  packages/g/gnome-bluetooth/package.yml
  packages/g/gnome-bluetooth/pspec_x86_64.xml
Labels: Blocked: ISO

#4889 bluejay: Add at v1.0.1
  packages/b/bluejay/MAINTAINERS.md
  packages/b/bluejay/abi_used_libs
  packages/b/bluejay/abi_used_symbols
  packages/b/bluejay/monitoring.yaml
  packages/b/bluejay/package.yml
  packages/b/bluejay/pspec_x86_64.xml
Labels: Topic: Sync Notes
